name: Hermes Agent Upstream
version: 0.1.1
slug: hermes_agent_upstream
description: Minimal HAOS wrapper around the official NousResearch Hermes Agent image
url: https://github.com/cavamora/hassio-addons/tree/main/hermes-agent-upstream
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
panel_icon: mdi:robot-outline
panel_title: Hermes Agent
map:
  - addon_config:rw
  - media:rw
  - share:rw
options:
  profiles_to_start:
    - diva
schema:
  profiles_to_start:
    - str
